# SITE CONFIGURATION
baseurl: "/personal_website"
url: "https://sigfrido11.github.io"

# THEME-SPECIFIC CONFIGURATION
title: Giuseppe Luciano                                  # site's title
description: "Sito personale di Giuseppe Luciano (anche cercato come Gkiuseppe Luciano) con post e progetti."      # used by search engines
keywords: ["Giuseppe Luciano", "Gkiuseppe Luciano", "blog", "portfolio", "progetti"]
alternate_names: ["Gkiuseppe Luciano"]
avatar: assets/logo.jpeg                       # Empty for no avatar in navbar
favicon: assets/logo.jpeg                             # Icon displayed in the tab

# Header and footer text
header_text: Giuseppe Luciano   # Change Blog header text
header_feature_image: assets/img/header/collision.webp
header_feature_image_responsive: true
footer_text: >
  Powered by Giuseppe Luciano with <a href="https://jekyllrb.com/">Jekyll</a> <a href="https://github.com/sylhare/Type-on-Strap">Type on Strap</a>

# Blog
excerpt: true                                           # Or "truncate" (first 250 characters), "false" to disable
post_navigation: true
color_image: /assets/img/lineart.png                    # A bit transparent for color posts.

# Features
# More in the _data folder for comments, share buttons, author and language
# For layout customization, go to the "_sass > base" folder, and check "_variables.scss"
katex: true                                             # Enable if using math markup
mermaid: default                                        # Enable mermaid-js for diagrams, use theme: base, forest, dark, default, neutral
google_analytics:                                       # Measurement ID, e.g. "G-00000"
cookie_consent: false                                   # To respect the usage of cookies
color_theme: auto                                       # auto, dark or light

# PAGINATION (jekyll-paginate-v2)
pagination:
  enabled: true
  per_page: 3
  permalink: "/page/:num/"
  title_suffix: " - page :num"
  sort_field: "date"
  sort_reverse: true

# PORTFOLIO
collections:
  portfolio:
    output: true
    permalink: /:collection/:name
  # translations removed (now using language-specific posts)

# BUILD SETTINGS
sass:
  style: compressed
  quiet_deps: true
plugins: [jekyll-paginate-v2, jekyll-seo-tag, jekyll-feed, jekyll-remote-theme, jekyll-sitemap]
exclude: [".jekyll-cache", ".jekyll-metadata", ".idea", "vendor/*", "assets/node_modules/*", ".github/*"]

# theme: type-on-strap                                  # if using the theme as a jekyll theme gem
remote_theme: sylhare/Type-on-Strap                     # If using as a remote_theme in github
